language: node_js
node_js:
  - 13
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build ./project/udagram-feed-api -t somethingwicked/udagram-feed-api:latest
  - docker build ./project/udagram-user-api -t somethingwicked/udagram-user-api:latest
  - docker build ./project/udagram-frontend -t somethingwicked/udagram-frontend:latest
  - docker build ./project/udagram-reverse-proxy -t somethingwicked/udagram-reverse-proxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push somethingwicked/udagram-feed-api:latest
  - docker push somethingwicked/udagram-user-api:latest
  - docker push somethingwicked/udagram-frontend:latest
  - docker push somethingwicked/udagram-reverse-proxy:latest